from Resources.landmark_logic import SimpleLandmark, SphereLandmark

LANDMARKS = [
    SimpleLandmark('distal tibia midpoint',
                   "Choose the most distal midpoint of the diaphysis in a circular tibia transversal plane.",
                   r"Resources/descriptions/disttibiamiddpoint.png"),
    SimpleLandmark('proximal tibia midpoint',
                   "Choose the point in the middle of the diaphysis at the height of the foramen nutricum.",
                   r"Resources/descriptions/proxtibiamidpoint.png"),
    SimpleLandmark('lateral cochlea',
                   "Choose the most cranial point on the cochlea tibiae lateralis.",
                   r"Resources/descriptions/lateralcochlea.png"),
    SimpleLandmark('medial cochlea',
                   "Choose the most cranial point on the cochlea tibiae medialis.",
                   r"Resources/descriptions/medialcochlea.png"),
    SimpleLandmark('condylus medialis tibiae',
                   "Choose the most caudal point on the convex condyle surface.",
                   r"Resources/descriptions/condylusmedtibiae.png"),
    SimpleLandmark('condylus lateralis tibiae',
                   "Choose the most caudal point on the convex condyle surface.",
                   r"Resources/descriptions/condyluslateralistibiae.png"),
    SimpleLandmark('lateral condyle articulation point tibia',
                   "Choose the lowest midpoint of the condylus tibialis lateralis articulation groove.",
                   r"Resources/descriptions/latcondylearticulationpoint.png"),
    SimpleLandmark('medial condyle articulation point tibia',
                   "Choose the lowest midpoint of the condylus tibialis medialis articulation groove.",
                   r"Resources/descriptions/medialcondylearticulationpoint.png"),
    SimpleLandmark('medial cochlea articulation point tibia',
                   "Choose the lowest midpoint of the cochlea tibialis medialis articulation groove.",
                   r"Resources/descriptions/medcochleaarticulationpoint.png"),
    SimpleLandmark('lateral cochlea articulation point tibia',
                   "Choose the lowest midpoint of the cochlea tibialis lateralis articulation groove.",
                   r"Resources/descriptions/lateralcochleaarticulationpoint.png"),
    SimpleLandmark('medial talus',
                   "Choose the most dorsal point on the trochlea tali.",
                   r"Resources/descriptions/medialtalus.png"),
    SimpleLandmark('lateral talus',
                   "Choose the most dorsal point on the trochlea tali.",
                   r"Resources/descriptions/lateraltalus.png"),
    SimpleLandmark('Talus centre',
                   "Choose the center of the talus.",
                   r"Resources/descriptions/taluscentre.png"),
    SimpleLandmark('Metatarsal centre',
                   "Choose the center of the metatarsal bone, at the level used for the distal reference point of the tibial metatarsal angle.",
                   r"Resources/descriptions/metatarsalcentre.png"),
    SphereLandmark('medial femur condyle',
                   "Place the center inside the medial condyle, then adjust the sphere's radius until it best matches the condyle surface.",
                   r"Resources/descriptions/medfemurcondyle.png"),
    SphereLandmark('lateral femur condyle',
                   "Place the center inside the lateral condyle, then adjust the sphere's radius until it best matches the condyle surface.",
                   r"Resources/descriptions/lateralfemurcondyle.png"),
    SimpleLandmark('Femur midpoint 30%',
                   "Choose the point on one third of the height of the femur in the middle of the diaphysis.",
                   r"Resources/descriptions/proxfemurmidpoint.png"),
    SimpleLandmark('Femur midpoint 50%',
                   "Choose the point on two thirds of the height of the femur in the middle of the diaphysis",
                   r"Resources/descriptions/distfemurmidpoint.png"),
    SimpleLandmark('femur neck', 
                   "Choose the center of the proximal femoral metaphysis on the height of the highest elevation of the lesser trochanter.", 
                   r"Resources/descriptions/femurneck.png"),
    SphereLandmark('femur head',
                   "Place the center inside the femoral head, then adjust the sphere's radius until it best matches the articular surface.",
                   r"Resources/descriptions/point on femur head.png")
]